### ISSUE TITLE
Doesn't work on initial load - Obsidian 1.6.1

### ISSUE THREAD

**Issue by luckman212** [JonasDoesThings/obsidian-hide-folders#11] opened 2024-05-23 17:09 UTC
Since 1.6 (1.6.1 now) the plugin doesn't hide folder at first launch. Probably needs a delay or a wrapping inside of `onLayoutReady()`

**Comment by JonasDoesThings** [comment] 2024-05-28 19:39
Hope I will find time tomorrow after work. Thanks for the hint with delay/onLayoutReady, should hopefully be a quick fix then 🙏

**Comment by JonasDoesThings** [comment] 2024-05-29 10:45
Oh, just saw that 1.6.x is still an insider-build. Since I sadly do not have a paid catalyst license, I cannot work on the issue at this point of time. 

I will look into it, as soon as 1.6.x is available for me.

**Comment by luckman212** [comment] 2024-06-07 16:33
Hi @JonasDoesThings just a note that [1.6.2](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.6.2) was just made public!

**Comment by JonasDoesThings** [comment] 2024-06-07 19:38
Hi, thanks for the heads-up @luckman212 

I sadly could not reproduce the issue, but I added an additional call to the plugin's `processFolders` in the `onLayoutReady` callback. Could you please check if the issue still persists using the latest v1.4.1?

**Comment by luckman212** [comment] 2024-06-07 21:17
Checking...

**Comment by calmwaves111** [comment] 2024-06-12 03:34
+1，I had the same problem

**Comment by luckman212** [comment] 2024-06-12 13:30
I forked and fixed it, very simple patch - @calmwaves111 let me know if that works for you

**Comment by JonasDoesThings** [comment] 2024-06-12 16:05
Hm, makes sense. My test-vault and my normal vault both don't have these big plugins that take long on startup so that could have been the reason why I couldn't reproduce the issue myself.

I have now merged your PR @luckman212 and released a new version 1.4.2 with the changes.
Please report back if the issue is fixed for you too @calmwaves111 :)

I appreciate the help! Thx ❤️

**Comment by luckman212** [comment] 2024-06-13 16:23
Another possible workaround: ensure that the File Explorer is shown at startup:

```
app.workspace.ensureSideLeaf('file-explorer', 'left', { active: !0 });
```

**Comment by luckman212** [comment] 2024-06-22 21:29
New PR: https://github.com/JonasDoesThings/obsidian-hide-folders/pull/16

**Closed** 2024-06-26 17:23 UTC
